base/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.views import LogoutView
from rest_framework import routers
from django.conf.urls.static import static
router = routers.DefaultRouter()
router.register(r'teams',TeamApi)
router.register(r'tasks',TaskApi)
urlpatterns = [
  path('login/',CustomLoginView.as_view(), name = "login"),
  path('logout/',LogoutView.as_view(next_page = 'login'), name = 'logout'),
  path('register/',RegisterPage.as_view(), name = 'register'),
  path('team/<int:team_id>/',TeamList.as_view(), name= 'team'),
  path('hub/',HubView.as_view(),name='hub'),
  path('create_team',CreateTeam.as_view(), name = 'create_team'),
  path('delete/<int:pk>/', TaskDelete.as_view(), name='delete_task'),
  path('team/<int:pk>/create_task/',TaskCreate.as_view(),name = "task_create"),
  path('team/<int:team_id>/remove_member/<int:user_id>/',TeamMemberDelete.as_view(),name="deletemember"),
  path('friendslist/', FriendList.as_view(), name='friendslist'),
  path('confirm_task/<int:pk>/',TaskComplete.as_view(), name='confirm_task'),
  path('api-auth/',include('rest_framework.urls',namespace='rest_framework')),
  path('api', include(router.urls)),
  path('friend/handle/<int:request_id>/<str:action>/', HandleFriendRequestView.as_view(), name='handle_friend_request'),
  path("team/<int:team_id>/add_friends/", AddFriendToTeam.as_view(), name="add_friend_to_team"),
  path('edit_profile',EditProfile.as_view(),name= "edit_profile"),
  


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todoapp/base/urls.py
from django.urls import path, include
from .views import TeamList,CustomLoginView,RegisterPage,HubView,CreateTeam,TaskDelete,TaskCreate,TeamMemberDelete,AddFriendToTeamView,TeamApi,TaskApi,ProfileApi,TaskComplete
from django.contrib.auth.views import LogoutView
from rest_framework import routers
router = routers.DefaultRouter()
router.register(r'teams',TeamApi)
router.register(r'tasks',TaskApi)
router.register(r'profiles',ProfileApi)
urlpatterns = [
  path('login/',CustomLoginView.as_view(), name = "login"),
  path('logout/',LogoutView.as_view(next_page = 'login'), name = 'logout'),
  path('register/',RegisterPage.as_view(), name = 'register'),
  path('team/<int:team_id>/',TeamList.as_view(), name= 'team'),
  path('hub/',HubView.as_view(),name='hub'),
  path('create_team',CreateTeam.as_view(), name = 'create_team'),
  path('delete/<int:pk>/', TaskDelete.as_view(), name='delete_task'),
  path('team/<int:pk>/create_task/',TaskCreate.as_view(),name = "task_create"),
  path('team/<int:team_id>/remove_member/<int:user_id>/',TeamMemberDelete.as_view(),name="deletemember"),
  path('add_friend_to_team/', AddFriendToTeamView.as_view(), name='add_friend_to_team'),
  path('confirm_task/<int:pk>/',TaskComplete.as_view(), name='confirm_task'),
  path('api-auth/',include('rest_framework.urls',namespace='rest_framework')),
  path('api', include(router.urls)),




]

todoapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('base.urls')),
    path('admin/', admin.site.urls),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.conf import settings
# Create your models here.


class Difficulty(models.Model):
    name = models.CharField(max_length=50) 
    max_xp = models.PositiveIntegerField()

    def __str__(self):
        return self.name
    
class CustomUser(AbstractUser):
    xp = models.IntegerField(default=0)
    level = models.IntegerField(default=1)
    podclass = models.TextField(null=True,blank=True)
    avatar = models.ImageField( upload_to="avatars/", null=True, blank=True)

class Task(models.Model):
    team = models.ForeignKey("Team", on_delete=models.CASCADE, null=True, blank=True, related_name="tasks")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True, related_name="tasks")
    title = models.CharField(max_length=200, null=True, blank=True)
    xp = models.IntegerField(null=True)
    description = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    difficulty = models.ForeignKey(Difficulty, on_delete=models.CASCADE)
    created = models.DateField(auto_now_add=True)
    


    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['complete']

class Team(models.Model):
    creator = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE, related_name="created_teams")
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="teams")  
    name = models.CharField(max_length=100) 
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name

todoapp/base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.conf import settings
# Create your models here.



class CustomUser(AbstractUser):
    xp = models.IntegerField(default=0)
    level = models.IntegerField(default=1)

class Task(models.Model):
    team = models.ForeignKey("Team", on_delete=models.CASCADE, null=True, blank=True, related_name="tasks")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True, related_name="tasks")
    title = models.CharField(max_length=200, null=True, blank=True)
    xp = models.IntegerField(null=True)
    description = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['complete']

class Team(models.Model):
    creator = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE, related_name="created_teams")
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="teams")  
    name = models.CharField(max_length=100) 
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name
    
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,null=True, blank=True, related_name="profile")
    friends = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='friends', blank=True)
    def __str__(self):
        return f"{self.user.username}"

base/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from friendship.models import Friend, FriendshipRequest
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from django.views import View
from django.contrib import messages
from django.contrib.auth import login
from rest_framework import viewsets
from .serializer import TeamSerializer,TaskSerializer
from .models import *
from django_ratelimit.decorators import ratelimit
from django.utils.decorators import method_decorator

User = get_user_model()
class CustomLoginView(LoginView):
    template_name = 'base/task_login.html'
    fields = '__all__'
    redirect_authenticated_user = True
    def get_success_url(self):
        return reverse_lazy('hub')
    

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2','podclass']


class RegisterPage(FormView):
    template_name = 'base/task_register.html'
    form_class = CustomUserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy("hub")
    
    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request,user)
        return super().form_valid(form)
    
    def get(self,*args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('tasks')
        return super(RegisterPage,self).get(*args, **kwargs)

class TeamList(LoginRequiredMixin,TemplateView):
    template_name = "base/task_list.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['teams'] = Team.objects.filter(members=self.request.user)
        team_id = self.kwargs.get('team_id')
        if team_id:
            context['team'] = Team.objects.get(id=team_id, members=self.request.user)
            context['tasks'] = Task.objects.filter(team_id=team_id, team__members=self.request.user) 
        else:
            context['tasks'] = Task.objects.filter(team__members=self.request.user)
        return context

class EditProfile(LoginRequiredMixin,UpdateView):
    model = CustomUser
    template_name = 'base/edit_profile.html'
    fields = ['podclass','avatar']
    success_url = reverse_lazy('hub')
    def get_object(self, queryset = ...):
        return self.request.user


class HubView(LoginRequiredMixin, TemplateView):
    template_name = "base/hub.html"  

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        
        context['user'] = user
        context['teams'] = Team.objects.filter(members=user)
        context['tasks'] = Task.objects.filter(user=user)
        return context
    def post(self, request, *args, **kwargs):
        user = request.user
        if "upgrade" in request.POST:
          while user.xp >= 1000:
            user.level += 1
            user.xp -= 1000
        user.save()
        return redirect('hub')

class CreateTeam(LoginRequiredMixin, CreateView):
    model = Team
    template_name = "base/create_team.html"
    fields = ['name']
    success_url = reverse_lazy('hub')
    def form_valid(self, form):
        form.instance.creator = self.request.user
        member_usernames = self.request.POST.getlist('members')
        response = super().form_valid(form)
        form.instance.members.add(self.request.user)
        for username in member_usernames:
            user = User.objects.filter(username=username).first()
            if user and Friend.objects.are_friends(self.request.user, user):
                form.instance.members.add(user)
            else:
                messages.error(self.request, f'Пользователь {username} не является вашим другом.')
        messages.success(self.request, 'Команда создана!')
        return response
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['friends'] = Friend.objects.friends(user=self.request.user)
        return context
    
class TaskDelete(LoginRequiredMixin,DeleteView):
    model = Task
    context_object_name = "taskd"
    success_url = reverse_lazy("hub")
    template_name = "base/delete_task.html"

class TeamMemberDelete(LoginRequiredMixin, View):
    template_name = "base/delete_from_team.html"
    def post(self, request, team_id, user_id):
        team = get_object_or_404(Team, pk=team_id)
        user = get_object_or_404(User, pk=user_id)

        if request.user == team.creator or request.user.is_superuser:
            team.members.remove(user)
            return redirect('team', team_id=team.id)
        

class TaskCreate(LoginRequiredMixin,View):
    def get(self, request, pk):
        team = get_object_or_404(Team, id=pk)
        members = team.members.all()
        diff = Difficulty.objects.all()
        return render(request, 'base/create_task.html', {
            'team': team,
            'members': members,
            'diff':diff
        })
        
    def post(self, request, pk):
        team = get_object_or_404(Team, id=pk)
        title = request.POST.get('title')
        user_id = request.POST.get('user')
        difficulty_id = request.POST.get('difficulty')
        difficulty = get_object_or_404(Difficulty, id=difficulty_id)
        user = get_object_or_404(User, id=user_id)
        xp = request.POST.get('xp')
       
        try:
            xp = int(xp)
        except ValueError:
            messages.error(request, "XP должно быть числом.")
        if xp > difficulty.max_xp:
            messages.error(request, f"XP не может превышать лимит сложности ({difficulty.max_xp}).")
            return redirect(request.path)
        if xp < 0:
            messages.error(request, f"XP не может быть меньше нуля")
            return redirect(request.path)
        

        Task.objects.create(title=title, user=user, team=team,xp=xp,difficulty=difficulty)

        return redirect('hub')



class FriendList(LoginRequiredMixin, View):
    template_name = 'base/status.html'
    login_url = '/login/'

    def post(self, request,):
        
        username = request.POST.get('username')
        to_user = User.objects.filter(username=username).first()

        if not to_user:
            messages.error(request, 'Пользователь не найден.')
            return redirect('friendslist')

        if to_user == request.user:
            messages.error(request, 'Нельзя добавить себя в друзья.')
            return redirect('friendslist')

        if Friend.objects.are_friends(request.user, to_user):
            messages.error(request, 'Вы уже друзья.')
            return redirect('friendslist')
        

        Friend.objects.add_friend(
            from_user=request.user,
            to_user=to_user,
            message="Привет! Хочу добавить тебя в друзья."
        )
        messages.success(request, 'Запрос на дружбу отправлен!')
        return redirect('hub')

    def get(self, request):
        friend_requests = Friend.objects.unrejected_requests(user=request.user)
        friends = Friend.objects.friends(user=request.user)
        teams = Team.objects.filter(members=request.user)
        all_users = User.objects.exclude(id=request.user.id)
        return render(request, self.template_name,{
            'friend_requests': friend_requests,
            'friends': friends,
            'teams': teams,
            'all_users': all_users
        })

class TeamApi(viewsets.ModelViewSet):
    queryset = Team.objects.all().order_by('name')
    serializer_class = TeamSerializer

class TaskApi(viewsets.ModelViewSet):
    queryset = Task.objects.all().order_by('title')
    serializer_class = TaskSerializer




class TaskComplete(LoginRequiredMixin, View):
    template_name = "base/confirm_task.html"

    def get(self, request, pk, *args, **kwargs):
       
        task = get_object_or_404(Task, id=pk, team__members=request.user)
        return render(request, self.template_name, {"task": task})

    def post(self, request, pk, *args, **kwargs):
        current_user = request.user
  
        task = get_object_or_404(Task, id=pk, team__members=current_user)
        if task.complete:
            messages.warning(request, "Эта задача уже выполнена.")
            return redirect(request.META.get("HTTP_REFERER", "/"))

        task.complete = True
        task.save()
        
        user = task.user
        if user:
            user.xp += task.xp or 0
            user.save()
        return redirect('hub')


class SendFriendRequestView(View):
    template_name = 'base/status.html'

    def post(self, request, user_id):
        to_user = User.objects.get(id=user_id)
        Friend.objects.add_friend(
            from_user=self.request.user,
            to_user=to_user,
            message="Привет! Хочу добавить тебя в друзья."
        )
        messages.success(self.request, 'Запрос на дружбу отправлен!')
        return redirect('friend_requests') 

    def get(self, request, user_id):
        return render(self.request, self.template_name)

class HandleFriendRequestView(LoginRequiredMixin, View):
    login_url = '/login/'

    def get(self, request, request_id, action):
        try:
            friend_request = FriendshipRequest.objects.get(id=request_id)
        except FriendshipRequest.DoesNotExist:
            messages.error(request, 'Запрос на дружбу не найден.')
            return redirect('add_friend_to_team')
        
        if request.user != friend_request.to_user:
            messages.error(request, 'У вас нет прав для этого действия.')

base/templates/base/add_friend_to_team.html
{% extends 'base/main.html' %}
{% load static %}
{% block css %}{% static "css/add_friend_to_team.css" %}{% endblock css %}

{% block content %}

<div class="hub-main">
    <h2>Добавить друзей в команду</h2>

    {% if friends %}
    <form method="post">
        {% csrf_token %}
        <a href="{% url 'hub' %}" class="back-link">&#8592; Вернуться назад</a>
        <ul class="friend-list">
            {% for friend in friends %}
                {% if friend not in team.members.all %}
                    <li>
                        <label>
                            <input type="checkbox" name="friends" value="{{ friend.id }}">
                            {{ friend.username }}
                        </label>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
        <button type="submit" class="btn btn-success">Добавить выбранных</button>
    </form>
{% else %}
    <p>У тебя пока нет друзей 😢 или твой друг уже в команде </p></br>
    <p>Вернутся <a href = '{% url "hub" %}'> назад</a></p>
{% endif %}
</div>
{% endblock content %}

base/templates/base/confirm_task.html
{% extends 'base/main.html' %}
{% load static %}
{% block css %}{% static "css/confirm_task.css" %}{% endblock css %}

{% block content %}
<div class="hub-main">

    <a href="{% url 'hub' %}" class="back-link">&#8592; Вернуться назад</a>

    <h2>Подтверждение выполнения</h2>
    <p>Вы уверены, что хотите завершить задачу "{{ task.title }}" и получить {{ task.xp }} XP?</p>
    
    <form method="post">
        {% csrf_token %}
        <button type="submit">Да</button>
        <a href="{% url 'hub' %}">Отмена</a>
    </form>

    </div>
</div>
{% endblock content %}

base/templates/base/create_task.html
{% extends 'base/main.html' %}
{% load static %}
{% block css %}{% static "css/task_create.css" %}{% endblock css %}

{% block content %}
<div class="hub-main">

    <div class="create-task-card">
        <h1>Создание задачи для команды "{{ team.name }}"</h1>

        <form method="POST">
            {% csrf_token %}

            <label for="id_title">Название задачи</label>
            <input type="text" name="title" id="id_title" required>

            <label for="id_xp">XP (награда)</label>
            <input type="number" name="xp" id="id_xp" required>

            <label for="id_user">Назначить исполнителя</label>
            <select name="user" id="id_user">
                {% for member in members %}
                    <option value="{{ member.id }}">{{ member.username }}</option>
                {% endfor %}
            </select>
            <label for="diff">Назначить сложность</label>
            <select name="difficulty" id="id_difficulty">
                {% for difficult in diff %}
                    <option value="{{ difficult.id }}">{{ difficult.name }}</option>
                {% endfor %}
            </select>
            {% if messages %}
            {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}

            <input type="submit" value="Создать" class="complete-btn" id="create-task-btn">
        </form>
 
<script>
    const btn = document.getElementById("create-task-btn");
    const form = btn.closest("form");

    form.addEventListener("submit", function() {
        btn.disabled = true;         
        btn.value = "Создаётся...";   
    });
</script>
        

        <a href="{% url "team" team.pk %}" class="back-link">← Вернуться к команде</a>
    </div>

</div>
{% endblock content %}

base/templates/base/create_team.html
{% extends "base/main.html" %}
{% load static %}
{% block css %}{% static "css/team_create.css" %}{% endblock css %}
{% block content %}
<div class="container">
    <h1>Создать команду</h1>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <label for="members">Выберите друзей:</label>
        <select name="members" id="members" multiple>
            {% for friend in friends %}
                <option value="{{ friend.username }}">{{ friend.username }}</option>
            {% endfor %}
        </select>
        <input type="submit" value="Создать команду">
    </form>
    <p>Вернуться в <a href="{% url 'hub' %}">Хаб</a></p>
</div>
{% endblock content %}

base/templates/base/delete_from_team.html
{% extends 'base/main.html' %}
{% load static %}
{% block css %}{% static "css/delete.css" %}{% endblock css %}

{% block content %}
<div class="hub-main">

    <a href="{% url 'hub' %}" class="back-link">&#8592; Вернуться назад</a>

    <div class="delete-card">
        <h2>Удаление участника команды</h2>
        <p>Вы уверены, что хотите удалить этого участника:<strong>{{ deletemember }}</strong> ?</p>
        <form method="POST">
            {% csrf_token %}
            <input type="submit" value="Удалить" class="complete-btn">
        </form>
    </div>
</div>
{% endblock content %}

base/templates/base/delete_task.html
{% extends 'base/main.html' %}
{% load static %}
{% block css %}{% static "css/delete.css" %}{% endblock css %}

{% block content %}
<div class="hub-main">

    <a href="{% url 'hub' %}" class="back-link">&#8592; Вернуться назад</a>

    <div class="delete-card">
        <h2>Удаление задачи</h2>
        <p>Вы уверены, что хотите удалить задачу: <strong>{{ taskd }}</strong> ?</p>
        <form method="POST">
            {% csrf_token %}
            <input type="submit" value="Удалить" class="complete-btn">
        </form>
    </div>
</div>
{% endblock content %}

base/templates/base/edit_profile.html
{% extends 'base/main.html' %}
{% load static %}
{% block css %}{% static "css/confirm_task.css" %}{% endblock css %}

{% block content %}
<div class="hub-main">

    <a href="{% url 'hub' %}" class="back-link">&#8592; Вернуться назад</a>

<form method="POST" enctype='multipart/form-data'>
    {{form.as_p}}
    {% csrf_token %}
    <input type="submit" value="Изменить профиль" class="complete-btn">
</form>
    </div>
</div>
{% endblock content %}

base/templates/base/hub.html
{% extends 'base/main.html' %}
{% load static %}

{% block css %}
  {% static "css/hub.css" %} 
{% endblock %}

{% block content %}

<!-- Сайдбар теперь ВНЕ hub-container -->
<aside class="sidebar">
    <button class="sidebar-button add-team-btn">
        <span class="icon"><a href="{% url "hub" %}">🏠</a></span>
    </button>
    <h2 class="sidebar-title">Команды</h2>
    {% if teams %}
    {% for team in teams %}
    <a href = "{% url "team" team.pk %}">
        <button class="sidebar-button">{{ team.name }}</button>
    </a>
    {% endfor %}
{% else %}
    <p>No teams found</p>
{% endif %}
<a href = "{% url "create_team" %}">
    <button class="sidebar-button add-team-btn">
        <span class="icon">+</span>
    </button>
</a>

<form method="post" action="{% url 'logout' %}">
    {% csrf_token %}
    <a href="{% url 'logout' %}">
        <button class="sidebar-button settings-btn">
            <span class="icon">🚪</span>
        </button>
    </a>
</form>
    <a href = "{% url "friendslist" %}">
    <button class="sidebar-button user-btn">
        <span class="icon">👤</span>
    </button>

</a>
</aside>

<div class="hub-container">
    <!-- Левая панель - информация о пользователе -->
    <aside class="profile-sidebar">
        {% if user.avatar %}
    <img src="{{ user.avatar.url }}" alt="avatar" class = "avatar">
{% endif %}
        <h2>{{ user.username }}</h2>
        <h1>{{user.podclass}}</h1>
        <p>Уровень: {{ user.level }}</p>
        <p>Опыт: {{ user.xp }} XP</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" name="upgrade" value="1" class="upgrade-btn">Прокачать героя</button>
        </form></br></br>
        <a href = "{% url "edit_profile" %}" class = "edit_profile">Изменить свой профиль<a>
    </aside>

    <!-- Центральная часть - список команд и задач -->
    <main class="hub-main">
        <h1>RPG ХАБ</h1>

        <section class="teams">
            <h2>Мои Команды</h2>
            {% for team in teams %}
                <h3>{{ team.name }}</h3>
                <p>Участников: {{ team.members.count }}</p>
            {% empty %}
                <p>У тебя пока нет команд.</p>
            {% endfor %}
            
        </section>

        <section class="tasks">
            <h2>Мои Квесты</h2>
            {% for task in tasks %}
                <div class="task-card">
                    <h3>{{ task.title }}</h3>
                    <p>Награда: +{{ task.reward.xp }} XP</p>
                    <button class="complete-btn">Выполнить</button>
                </div>
            {% empty %}
                <p>Нет активных квестов.</p>
            {% endfor %}
        </section>
    </main>

    <!-- Правая панель - Лидерборд и награды -->
    <aside class="leaderboard">
    

        <h2>Награды</h2>
        {% for reward in rewards %}
            <div class="reward-card">
                <h3>{{ reward.task.title }}</h3>
                <p>+{{ reward.xp }} XP</p>
            </div>
        {% empty %}
            <p>Нет наград.</p>
        {% endfor %}
    </aside>
</div>

{% endblock %}

base/templates/base/main.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}

<head>
    <meta charset="utf-8">
    <meta name="description"
        content="This is to do list implemented using Django by Dennis Ivy who is a full stack web developer.">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>To Do Items</title>
    <link rel="stylesheet" href="{% block css %}{% endblock css %}">
    

    
</head>

<body>

    <div class="container">
        {% block content %} {% endblock content %}
    </div>

</body>


</html>

base/templates/base/profile.html
{% extends "base/main.html" %}
{% load static %}
{% block css %}{% endblock css %}

{% block  %}{% endblock  %}

base/templates/base/task_login.html
{% extends 'base/main.html' %}
{% load static %}
{% block css %}
{% static 'css/login.css' %}
{% endblock css %}
{% block content %}

<div class="header-bar">
    <h1>Login</h1>
</div>

<form method = "POST">

{% csrf_token %}

{{form.as_p}}

<input type = "submit" value = "Login"> 

<form>

<p>Dont have an account ?<a href = "{% url "register" %}">Register</a></p>


{% endblock content %}

base/templates/base/task_register.html
{% extends 'base/main.html' %}
{% load static %}

{% block css %}{% static "css/register.css" %}{% endblock css %}
{% block content %}

<div class="header-bar">
    <h1>Register</h1>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}

        <label>{{form.username.label}}</label>
        {{form.username}}


        <label>{{form.podclass.label}}</label>
        {{form.podclass}}


        
        <label>{{form.password1.label}}</label>
        {{form.password1}}

        <label>{{form.password2.label}}</label>
        {{form.password2}}
        <input style="margin-top:10px ;" class="button" type="submit" value="Register">
    </form>
    <p>Already have an account? <a href="{% url 'login' %}">Login</a></p>
</div>

{% endblock content %}